files_location:
  directory_path: '/Users/michaelr/Documents/TRAVAIL/AUTOENTREPRENEUR/7 Clients/Meagan Butters - Ardo/data/'

filenames:
  port_shipping: 'Rates Project - 1 - Arrival_at_Port.csv'
  ocean_shipping: 'Rates Project - 2 - Ocean_Freight.csv'
  drayage_shipping: 'Rates Project - 3 - Drayage.csv'
  truck_shipping: 'Rates Project - 4 - Point to Point.csv'

csv_options:
  col_sep: ','
  quote_char: '"'
  headers: :first_row

query_defaults:
  default_container_type: '40 ft reefer'

expiry_email:
  default: 'sunsmiley@live.fr'
  ocean_freight_csv_column_for_email: 'email'

headers_port_shipping:
  supplier: 'Supplier'
  place_of_loading: 'Place of Loading'
  port_of_loading: 'Port of Loading'
  forwarder: 'Forwarder'
  transit_time: 'Transit Time'
  cost: 'Cost'
  currency: 'Currency'
  notes: 'Notes'
headers_ocean_shipping:
  carrier: 'Carrier'
  country_of_origin: 'Country of Origin'
  country_of_destination: 'Country of Destination'
  port_of_loading: 'Port of Loading'
  port_of_destination: 'Port of Destination'
  container_type: 'Container Type'
  transit_time: 'Transit Time'
  cost: 'Cost'
  currency: 'Currency'
  expiry: 'Expiry'
  notes: 'Notes'
headers_drayage_shipping:
  port_of_destination: 'Port of Destination'
  place_of_delivery: 'Place of Delivery'
  max_gross_cargo: 'Max gross cargo (Lbs)'
  transit_time: 'Transit Time'
  cost: 'Cost'
  currency: 'Currency'
  notes: 'Notes'
headers_truck_shipping:
  place_of_loading: 'Place of Loading'
  place_of_delivery: 'Place of Delivery'
  trucker: 'Trucker'
  max_gross_cargo: 'Max gross cargo (Lbs)'
  transit_time: 'Transit Time'
  cost: 'Cost'
  currency: 'Currency'
  notes: 'Notes'

currency_rates_to_usd:
  EUR: 1.222499866
  AED: 0.2722940776
  ALL: 0.009900000099
  AUD: 0.7740770872
  BGN: 0.6250640691
  BND: 0.7578628268
  BRL: 0.1922290632
  CAD: 0.8311805756
  CHF: 1.112780282
  CLP: 0.001384830566
  CNY: 0.1566444258
  CZK: 0.04801272452
  DKK: 0.1643896508
  GBP: 1.416815905
  HKD: 0.1288836344
  HRK: 0.1628154835
  HUF: 0.003528545864
  IDR: 0.00007015137778
  ILS: 0.3084940124
  INR: 0.0137181522
  JPY: 0.009119731422
  KRW: 0.0009019544194
  KWD: 3.325020781
  MKD: 0.0198019802
  MXN: 0.05025094569
  MYR: 0.2423383518
  NOK: 0.1209043354
  NZD: 0.7260793169
  OMR: 2.600780234
  PEN: 0.2603149811
  PHP: 0.02093106878
  PLN: 0.2737287217
  QAR: 0.2747252747
  RON: 0.2485210512
  RUB: 0.01359673361
  SEK: 0.1210935523
  SGD: 0.7560762064
  THB: 0.03208240404
  TRY: 0.117365258
  TTD: 0.1483503442
  ZAR: 0.07264462164